main: br.com.battlebits.ylobby.LobbyMain
version: 2.0
authors: [zViitoor, GustavoInacio]
name: Lobby
website: www.battlebits.com.br
description: Plugin do Lobby da BattleBits Network.
depend: [Commons, HolographicDisplays, Citizens]
loadbefore: [Commons, HolographicDisplays, Citizens]